---
name: Jonas
surname: Weinert
position: "Data Scientist & Global Health Economist"
#www: "github.com/JonasWeinert"
email: "jonas.weinert@icloud.com"
phone: +44 7987419642
github: JonasWeinert
linkedin: jweinert1997
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 2E2E2E
aboutme: "Economics & econometrics nerdwith a passion for expeerimental and quasi-experimental causal inference in impact evaluations. I am also fascinated with finding ways to leverage data and technology to generate visualisations, graphs and other inisights in organisational settings."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} - {endYear}",.na = ""),
    where = where
  )

```

# Professional experience

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Data Science Projects & Products

```{r PROJECTS}

projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```




<!-- # Certifications -->

<!-- ```{r CERTIFICATIONS} -->

<!-- certifications %>% -->
<!--   detailed_entries( -->
<!--     with = area, -->
<!--     what = accomplishment, -->
<!--     why = detail, -->
<!--     when = year, -->
<!--     where = where -->
<!--   ) -->

<!-- ``` -->
